### PR TITLE
Updated CfP spec, proposals form

### PR DESCRIPTION
**Pull request by shlomi-noach**
### Work in Progress

This PR updates the CfP spec according to the RS19 CfP Spec paper.

### CODE REVIEW

**Comment by shlomi-noach** [comment]
This PR is ready for review. I've tested it on my local box.

TL;DR:

- Rewrote CfP spec according to internal Paper document.
- Rewrite to parts of the submission form:
  - Added "Postmortems (15 min)" submissions.
  - Edited (simplified) categories.
  - Added some guidance comments.

**Comment by rantav** [comment]
lgtm. 

Going forward I believe most of the PRs should be reviewed and merged by @neta-kedem bus since I already pulled and ran and tested everything I'll go ahead and merge

**Comment by shlomi-noach** [comment]
Does this auto-deploy?

**Comment by rantav** [comment]
yes, no merge to master
I can give you access to heroku if you're interested.

**Comment by shlomi-noach** [comment]
merge-to-master works for me.

**Pull request merged**
